[package]
name = "cli"
authors = [ "Redblox Organization" ]
description = "A blazingly fast networking solution for Roblox."
version = "0.6.26"
edition = "2024"

[dependencies]
anyhow = "1.0"
codespan-reporting = "0.12.0"

[dependencies.clap]
version = "4.4.11"
features = [ "derive" ]

[dependencies.zap]
path = "../zap"

[[bin]]
name = "zap"
path = "src/main.rs"
