[package]
name = "zap"
authors = [ "Redblox Organization" ]
description = "A blazingly fast networking solution for Roblox."
version = "0.6.26"
edition = "2024"

[lib]
crate-type = [ "lib", "cdylib" ]

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
codespan-reporting = "0.12.0"
lalrpop-util = "0.22.2"
num-traits = "0.2.17"
wasm-bindgen = "0.2"

[dev-dependencies]
anyhow = "1.0"
selene-lib = "0.28.0"
serde_yml = "0.0.12"
toml = "0.8.19"

[dev-dependencies.full_moon]
version = "1.2.0"
features = [ "luau" ]

[dev-dependencies.insta]
version = "1.42.0"
features = [ "glob" ]

[dev-dependencies.lune]
git = "https://github.com/lune-org/lune.git"
rev = "5d1401cdf611cc9f215f03bdf16ada0e77717edf"

[dev-dependencies.tokio]
version = "1"
features = [ "full" ]
